# Uncomment the next line to define a global platform for your project
# source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'

target 'snapkitT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for snapkitT
  pod 'SnapKit', '~> 5.0'

end
