os: osx
osx_image: xcode10
language: swift
# Build the main app, which happens to depend on the test cases.
script: xcodebuild clean build test -workspace TravisCI.xcworkspace -scheme TravisCI -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.0,name=iPhone 7" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO